config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  root to: "discussions#index"

  resources :discussions
  resources :chats do

  end
  get 'chats/:id/discussion' => 'chats#discussion', as: :discussion_on
  post 'discussions/:id/join_discussion'=> 'discussions#join_discussion', as: :join_discussion

end

app/models/chat.rb
class Chat < ActiveRecord::Base
	belongs_to :user
	belongs_to :discussion
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	belongs_to :user
	has_many :chats
	has_many :discussion_members
	acts_as_slugable :source_column => :title, :target_column => :slug, :slug_column => :slug
	scope :published, where("published=1") 
	scope :descending, order("#{self.table_name}.created_at DESC")
	
	def to_param
    	slug
  	end
end

app/models/discussion_member.rb
class DiscussionMember < ActiveRecord::Base
	has_many :users
	has_many :dicussions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chats
  has_many :discussions         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!


end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_filter :find_discussion, only: [:discussion, :create]

  def discussion
    @member = DiscussionMember.find_by_discussion_id_and_user_id(@discussion.id, current_user.id )
    if @member
      @chats = @discussion.chats
    end  
  end

  def show

  end

  def new
    
  end

  def create
    @chat = Chat.new(chat_params)
    @channel = params[:id]
    @discussion = Discussion.find_by_slug(params[:id])
    user = User.find_by_email(params[:login])
    @msg = 0
    if user and user == current_user
      @chat.user_id = current_user.id
      @chat.channel_id = 1
      @chat.discussion_id = @discussion.id
      @chat.save
      PrivatePub.publish_to("/chats/#{@channel}", "#{@chat.message}")
      @msg = 1
    end
    # respond_to do |format|
    #   format.js 
    # end
  end

  def update
  end

  def destroy
  end

  protected

  def chat_params
      params.require(:chat).permit(:user_id, :message)
  end

  def find_discussion
    @discussion = Discussion.find_by_slug(params[:id]) or raise(ActiveRecord::RecordNotFound) if params[:id]
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

before_filter :find_discussion
before_filter :check_owner, only: [:destroy, :update, :edit]

  def index
  	@discussions = Discussion.all
  end

  def new
  	@discussion = Discussion.new
  end

  def edit

  end

  def create
  	@discussion = Discussion.new(discussion_params)
  	@discussion.user_id = current_user.id
  	if @discussion.save
  		@discussion_member = DiscussionMember.new
		@discussion_member.user_id = current_user.id
		@discussion_member.discussion_id = @discussion.id
		@discussion_member.save
  		flash[:notice] = "Discussion created successfully"
  		redirect_to discussion_on_path(id: @discussion.slug )
  	end
  end

  def update
	  @discussion.update_attributes(discussion_params)
    flash[:notice] = "Discussion updated successfully"
    redirect_to discussion_on_path(id: @discussion.slug )
  end

  def join_discussion
  	if @discussion.secret_key == params[:discussion][:secret_key]
  		@discussion_member = DiscussionMember.find_by_discussion_id_and_user_id(@discussion.id, current_user.id)
  		if @discussion_member
  			flash[:notice]="You have already joined the discussion."
  			redirect_to discussion_on_path(@discussion)
  		else
  			@discussion_member = DiscussionMember.new
  			@discussion_member.user_id = current_user.id
  			@discussion_member.discussion_id = @discussion.id
  			@discussion_member.save
  			flash[:notice]="You have joined the discussion successfully."
  			redirect_to discussion_on_path(@discussion)
  		end
  	else
  		flash[:error]="You have entered a wrong key."
  		redirect_to discussion_on_path(@discussion)	
  	end
  end

  def destroy
  		@discussion.destroy
  		flash[:notice] = "Discussion has been successfully removed."
  		redirect_to discussions_path
  end

  def show
  	@chats = @discussion.chats if @discussion
  end

  protected 

  def discussion_params
      params.require(:discussion).permit(:secret_key, :title, :description)
  end

  def find_discussion
  	@discussion = Discussion.find_by_slug(params[:id]) or raise(ActiveRecord::RecordNotFound) if params[:id]
  end

  def check_owner
  	if current_user.id == @discussion.user_id or current_user.email = "sahilprjpt206@gmail.com"
  		return true
  	else
  		flash[:error] = "Access Denied"
  		redirect_to discussions_path
  	end	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/chats/_user_message.html.erb
<% if current_user.id == chat.user.id %>
  <div class="userPost col-lg-12 col-md-12">
    <div class="col-lg-10 col-md-6 paddingReset">
      <div class="userBubble clearfix"> 
        <i class="fa fa-caret-right fa-4x white"></i>
        <div class="col-lg-12 col-md-12 paddingReset">
            <img class="media-object media-object-right img-circle hidden-xs hidden-sm" src="http://api.randomuser.me/portraits/med/women/64.jpg" alt="user pic">
            <div>
              <a href="#"> <h4 style="margin-bottom:5px; display:inline-block;"> <span> <strong> <%= chat.user.email %> </strong> </span> </h4></a>
              <a style="text-decoration:none;" href="#"> <span class="text-muted small"> • <%= time_ago_in_words(chat.created_at).capitalize %> Ago </span> </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 paddingReset margin-top-xs message"> 
          <%= chat.message %>
        </div>
      </div>
    </div>
  </div>

<% elsif current_user.id != chat.user.id %>
  <div class="userPost col-lg-12 col-md-12">
    <div class="col-md-offset-2 col-lg-offset-2 col-lg-10 col-md-6 paddingReset">
      <div class="userBubble clearfix"> 
        <i class="fa fa-caret-left fa-4x white"></i>
        <div class="col-lg-12 col-md-12 paddingReset">
            <img class="media-object media-object-left img-circle hidden-xs hidden-sm" src="<%= asset_path('7.jpg') %>" alt="user pic">
            <div>
              <a href="#"> <h4 style="margin-bottom:5px; display:inline-block;"> <span> <strong> <%= chat.user.email %> </strong> </span> </h4></a>
              <a style="text-decoration:none;" href="#"> <span class="text-muted small"> • <%= time_ago_in_words(chat.created_at).capitalize %> Ago </span> </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 paddingReset margin-top-xs message"> 
          <%= chat.message %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/chats/create.js.erb
<%# if @msg == 1 %>
    PrivatePub.subscribe("/chats/<%= @discussion.slug %>", function(data, channel) {
      $(".discBox").append(data.message);
    });

	<% publish_to "/chats/#{ @channel }" do %>
		$('#message_box').val('');
		$('.discBox .userPost').removeClass('new');
		$('.discBox').append("<%= j render :partial => '/chats/user_message', :locals=>{:chat => @chat}, :object=> current_user %>").find('.userPost:last').addClass('new');
	<% end %>
<%# end %>

app/views/chats/destroy.html.erb
<h1>Chats#destroy</h1>
<p>Find me in app/views/chats/destroy.html.erb</p>

app/views/chats/discussion.html.erb
<div class="col-lg-3 col-md-10 col-sm-12 col-xs-12 margin-top-md">
  
</div>

<div class="col-lg-8 col-md-11 col-sm-12 col-xs-12 margin-top-md" style="margin-top: -36px;">
    <div class="h4 raleway"><a class="text-muted" href="/">HOME</a> >> <%= @discussion.title %></div>
    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 paddingReset commentContainer"> 

      <% if @member %>
        <div class="discBox col-lg-10 col-md-10 col-sm-10 col-xs-12 paddingReset">
       	<% if @chats %>
  	      	<% @chats.each do |chat| %>
  	      		<%= render partial: 'user_message', locals: {:chat => chat } %>
  	      	<% end %>
        	<% end %> 	
        </div>


        <div class="messageBox col-lg-10 col-md-10 col-sm-10 col-xs-12 paddingReset">
        	<%= form_tag "/chats",:method=> 'post', remote: true do %>
        		<%= hidden_field_tag 'login',current_user.email %>
            <%= hidden_field_tag 'id', @discussion.slug %>
        		<div class="form-group">
  	      		<textarea class="form-control" value="" id="message_box" name="chat[message]" ></textarea>
              <p class="help-block">(Press <kbd>ENTER</kbd> to comment)</p>
        		</div>
        		<button class="btn btn-sm btn-info hidden">Submit</button>
        	<% end %>
        </div>
      <% else %>
        <div class="well h5"> You have not joined the discussion yet.
          Please enter the secret key and click on 'JOIN' button.
          <%= form_tag join_discussion_path(@discussion) do %>
            <div class="form-group margin-top-md">
              <label for="discussion_secret_key">Secret Key :</label> 
              <input id="discussion_secret_key" name="discussion[secret_key]" value="" placeholder="Please enter the secret key.." required class="form-control" />
            </div>
            <div class="form-group">
              <%= submit_tag 'JOIN', class: 'btn btn-info btn-sm' %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

<%= subscribe_to "/chats/#{@discussion.slug}" %>
<style type="text/css">
.discBox {
    border: 1px solid #666;
    height: 400px;
    margin-bottom: 10px;
    overflow: auto;
    background-color: #eee;
}
.message{
	margin-bottom: 10px;
}
.new > div{
	border-top: 1px solid dodgerblue;
    margin-top: 14px;
}
.paddingReset{
  padding-right: 0;
  padding-left: 0;
}
.messageBox{
background: rgba(255,255,255,0.7);
padding: 4px 11px;
border-radius: 3px;
}
</style>
<script>
  $(document).ready(function(){
    $('#message_box').on('keydown', function(e){
      var key_pressed = e.which;
      if(key_pressed === 13 ){
        if($(this).val()!== ""){
          $('.messageBox form button').trigger('click');
        }
      }
    });


  });
</script>

app/views/chats/edit.html.erb
<h1>Chats#edit</h1>
<p>Find me in app/views/chats/edit.html.erb</p>

app/views/chats/new.html.erb
<h1>Chats#new</h1>
<p>Find me in app/views/chats/new.html.erb</p>

app/views/chats/update.html.erb
<h1>Chats#update</h1>
<p>Find me in app/views/chats/update.html.erb</p>

app/views/discussions/_form.html.erb
<div class="h3 raleway"><%= controller.action_name.capitalize %> Discussion</div>
	<%= form_for @discussion, class: 'form' do |f| %>
		<div class="form-group">
			<label for="discussion_title"> Title :</label>
			<%= f.text_field :title, class: 'form-control', required: true %>
		</div>
		<div class="form-group">
			<label for="discussion_description"> Description :</label>
			<%= f.text_area :description, class: 'form-control', required: true %>
		</div>
		<div class="form-group">
			<label for="discussion_title"> Secret Key :</label>
			<%= f.text_field :secret_key, class: 'form-control', required: true %>
		</div>
		<div class="form-group">
			<% if controller.action_name == "new" %>
				<%= f.submit "CREATE", class: 'btn btn-success btn-sm' %>
			<% else %>	
				<%= f.submit "UPDATE", class: 'btn btn-success btn-sm' %>
			<% end %>	
		</div>		
	<% end %>

app/views/discussions/edit.html.erb
<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 margin-top-md">
</div>

<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 margin-top-md ccpPost">
	<%= render partial: 'form' %>
</div>

app/views/discussions/index.html.erb
<div class="col-lg-3 col-md-10 col-sm-12 col-xs-12 margin-top-md">
</div>

<div class="col-lg-8 col-md-11 col-sm-12 col-xs-12 margin-top-md" style="margin-top: -36px;">
  <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 ccpPost margin-top-md"> 
  <%= link_to 'New Discussion', new_discussion_path(), class: 'btn btn-success btn-md' %>
  <table class="table table-hover table-bordered margin-top-md">
    <thead>
      <tr>
        <th>S.No.</th>
        <th>Topic</th>
        <th>No. of Users</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% if @discussions %>
      <% @discussions.each_with_index do |discussion, index| %>
        <tr>
          <td><%= (index+1) %></td>
          <td><%= link_to discussion.title, discussion_on_path(discussion) %></td>
          <td class="text-center"><%= discussion.discussion_members.count %></td>
          <td> 
          		<%= link_to '<i class="fa fa-pencil"></i>'.html_safe,edit_discussion_path(discussion), class: 'btn btn-xs' %> 
          		<%= link_to '<i class="fa fa-trash-o"></i>'.html_safe,discussion_path(discussion), class: 'btn btn-xs', method: :delete, confirm: 'Are you sure?' %>
          </td>
        </tr>
      <% end %>  
    <% else %>
        <tr>
          <td colspan="4" class="text-center">No Discussions yet</td>
        </tr>
    <% end %>    
    </tbody>

  </table>
    
  </div>
</div>    

app/views/discussions/new.html.erb
<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 margin-top-md">
</div>

<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 margin-top-md ccpPost">
	<%= render partial: 'form' %>
</div>

app/views/discussions/show.html.erb
<h1>Discussions#show</h1>
<p>Find me in app/views/discussions/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
  <title>Discussion</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'chats' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- external font & css assets -->
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>


	<link rel="stylesheet" type = "text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<style type="text/css">
  .background {
      position: absolute;
      width: 100vw;
      background: url("/assets/background-min.jpg");
      background-position: center;
      background-size: cover;  
      height: 100vh;
      top: -1px;
      z-index: -1;
      background-size: cover;
    }
</style>
 <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default paddingReset navbar-inverse">
  <div class="container-fluid paddingReset">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand h3 raleway" href="/">LIVE DISCUSSIONS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
		
		  	<% if user_signed_in? %>
		    	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
		  	<% else %>
		    	<li><%= link_to "Sign up", new_user_registration_path %></li>
		    	<li> <%= link_to "Sign in", new_user_session_path %></li>
		  	<% end %>
		</ul>  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="pull-right col-md-12 col-sm-12 col-xs-12 col-lg-12 text-right">
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% end %>
</div>
<div class="background"></div>
<%= yield %>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>  
 <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
 <%= javascript_include_tag 'nanoScroll.js' %>
 <%= render partial: 'shared/ga' %>
 
 <script type="text/javascript">
 <% if flash[:notice] %>
    notification('<%= flash[:notice] %>','success');
 <% elsif flash[:error] %>
    notification('<%= flash[:error] %>','danger');
 <% end %>
   function notification(msg,type){
    var alert = $('<div class="alert notification-alert '+type+'-notification"></div>');
    $('body').append(alert);
    alert.html(msg);
    setTimeout(function(){
      $('.notification-alert').fadeOut().remove();
    },3000);
  }
 </script>
 <% if params[:controller] == "discussions" %>
  <div class="footer col-md-12 col-sm-12 col-xs-12 col-lg-12 text-center" style="">
    Created by: Sahil Prajapati | 
    <a href="https://github.com/sahil290791/discussions_app"><i class="fa fa-fw fa-github"></i></a>
    <a href="https://in.linkedin.com/in/sahil290791"><i class="fa fa-fw fa-linkedin"></i></a>
    <a href="https://twitter.com/@sahilprjpt206"><i class="fa fa-fw fa-twitter"></i></a>
    
</div>
<% end %>
</body>
</html>

app/views/shared/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV["GA_ID"] %>', 'auto');
  ga('send', 'pageview');

</script>